#!/usr/bin/env python3
"""Regenerate schema.sql (Supabase seed) from figures.json.

figures.json is the canonical dataset (kept in sync with the live Supabase
table `minifigures`). Run this after editing figures.json to refresh
schema.sql, then paste schema.sql into the Supabase SQL editor to reseed.

Note: the `minifig_prices` table (purchase prices) is intentionally NOT
seeded here — its data lives only in Supabase. This script only ensures the
table exists.
"""
import json

with open("figures.json", encoding="utf-8") as f:
    rows = json.load(f)


def sql_str(v):
    return "NULL" if v is None else "'" + str(v).replace("'", "''") + "'"


L = []
L.append("-- LEGO Minifigures collection — Supabase schema + seed")
L.append("-- Generated by gen_data.py from figures.json — do not edit by hand")
L.append("create table if not exists public.minifigures (")
L.append("  id bigserial primary key, name_th text not null, name_en text, series text,")
L.append("  set_no text, release_date text, release_sort integer not null default 99990000,")
L.append("  category text, bricklink_id text, image_url text, confidence text, emoji text,")
L.append("  identified boolean not null default true, note text, history text, inspiration text,")
L.append("  type text, created_at timestamptz not null default now()")
L.append(");")
L.append("alter table public.minifigures add column if not exists set_no text;")
L.append("alter table public.minifigures add column if not exists history text;")
L.append("alter table public.minifigures add column if not exists inspiration text;")
L.append("alter table public.minifigures add column if not exists type text;")
L.append("alter table public.minifigures enable row level security;")
L.append('drop policy if exists "public read" on public.minifigures;')
L.append('create policy "public read" on public.minifigures for select to anon, authenticated using (true);')
L.append("")
L.append("-- purchase-price log (data lives in Supabase only; never truncated here)")
L.append("create table if not exists public.minifig_prices (")
L.append("  id bigserial primary key, name_en text not null, price numeric,")
L.append("  currency text default 'THB', created_at timestamptz not null default now()")
L.append(");")
L.append("")
L.append("truncate table public.minifigures restart identity;")
cols = ("name_th, name_en, series, set_no, release_date, release_sort, category, "
        "bricklink_id, image_url, confidence, emoji, identified, note, history, inspiration, type")
L.append(f"insert into public.minifigures ({cols}) values")
vals = []
for r in rows:
    vals.append("  (" + ", ".join([
        sql_str(r["name_th"]), sql_str(r.get("name_en")), sql_str(r.get("series")), sql_str(r.get("set_no")),
        sql_str(r.get("release_date")), str(r.get("release_sort", 99990000)), sql_str(r.get("category")),
        sql_str(r.get("bricklink_id")), sql_str(r.get("image_url")), sql_str(r.get("confidence")),
        sql_str(r.get("emoji")), "true" if r.get("identified", True) else "false", sql_str(r.get("note")),
        sql_str(r.get("history")), sql_str(r.get("inspiration")), sql_str(r.get("type")),
    ]) + ")")
L.append(",\n".join(vals) + ";")
with open("schema.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")

print(f"rows={len(rows)} (sets={sum(1 for r in rows if r.get('category')=='set')}, "
      f"books={sum(1 for r in rows if r.get('category')=='book')}) -> schema.sql")
