-- LEGO Minifigures collection — Supabase schema + seed
create table if not exists public.minifigures (
  id bigserial primary key, name_th text not null, name_en text, series text,
  set_no text, release_date text, release_sort integer not null default 99990000,
  category text, bricklink_id text, image_url text, confidence text, emoji text,
  identified boolean not null default true, note text, history text, inspiration text, created_at timestamptz not null default now()
);
alter table public.minifigures add column if not exists set_no text;
alter table public.minifigures add column if not exists history text;
alter table public.minifigures add column if not exists inspiration text;
alter table public.minifigures enable row level security;
drop policy if exists "public read" on public.minifigures;
create policy "public read" on public.minifigures for select to anon, authenticated using (true);
truncate table public.minifigures restart identity;
insert into public.minifigures (name_th, name_en, series, set_no, release_date, release_sort, category, bricklink_id, image_url, confidence, emoji, identified, note, history, inspiration) values
  ('บัซ ไลต์เยียร์', 'Buzz Lightyear', 'LEGO Toy Story', NULL, '2010', 20100101, 'pop', 'toy004', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/toy004.png', 'fair', '🚀', true, NULL, 'Part of the LEGO Toy Story line (2010), released alongside the Toy Story 3 sets.', 'Buzz Lightyear, the Space Ranger action figure from Pixar''s Toy Story.'),
  ('วู้ดดี้', 'Woody', 'LEGO Toy Story', NULL, '2010', 20100102, 'pop', 'toy003', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/toy003.png', 'sure', '🤠', true, NULL, 'Released in 2010 with LEGO''s Toy Story theme.', 'Sheriff Woody, the pull-string cowboy doll and Andy''s favourite toy.'),
  ('ฟาโรห์', 'Pharaoh', 'Series 2', '8684', '2010', 20100901, 'myth', 'col032', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col032.png', 'fair', '🏺', true, NULL, 'Collectible Minifigures Series 2 (2010), an early CMF wave.', 'An ancient Egyptian pharaoh in golden ceremonial regalia.'),
  ('ราชาสมุทร / โพไซดอน', 'Ocean King (Poseidon)', 'Series 7', '8831', 'May 2012', 20120501, 'myth', 'col101', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col101.png', 'sure', '🔱', true, NULL, 'Collectible Minifigures Series 7 (2012).', 'A merman sea-king echoing Poseidon/Neptune, ruler of the oceans.'),
  ('ชุดไก่', 'Chicken Suit Guy', 'Series 9', '71000', 'Jan 2013', 20130101, 'animal', 'col135', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col135.png', 'sure', '🐔', true, NULL, 'CMF Series 9 (set 71000, 2013); one of LEGO''s most beloved costume figures.', 'A super-fan wearing a full chicken mascot suit.'),
  ('พ่อมด', 'Wizard', 'Series 12', '71007', '2014', 20140101, 'myth', 'col179', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col179.png', 'sure', '🧙', true, NULL, 'CMF Series 12 (71007, 2014).', 'A classic fantasy wizard with a star-and-moon robe and crystal staff.'),
  ('ชุดฮอตดอก', 'Hot Dog Man', 'Series 13', '71008', 'Jan 2015', 20150101, 'food', 'col208', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col208.png', 'sure', '🌭', true, NULL, 'CMF Series 13 (71008, 2015); an instant collector favourite.', 'A cheerful man dressed as a hot dog in a bun.'),
  ('ราชาคลาสสิก', 'Classic King', 'Series 13', '71008', 'Jan 2015', 20150102, 'castle', 'col195', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col195.png', 'sure', '👑', true, NULL, 'CMF Series 13 (71008, 2015).', 'A medieval king with golden crown and ermine cape, nodding to LEGO Castle.'),
  ('ชุดฉลาม', 'Shark Suit Guy', 'Series 15', '71011', 'Jan 2016', 20160101, 'animal', 'col240', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col240.png', 'sure', '🦈', true, NULL, 'CMF Series 15 (71011, 2016).', 'A goofy guy poking out of a foam shark costume.'),
  ('ชุดกล้วย', 'Banana Guy', 'Series 16', '71013', 'Sep 2016', 20160901, 'food', 'col258', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col258.png', 'sure', '🍌', true, NULL, 'CMF Series 16 (71013, 2016).', 'A man in a giant banana suit.'),
  ('เด็กชุดเพนกวิน', 'Penguin Boy', 'Series 16', '71013', 'Sep 2016', 20160902, 'animal', 'col253', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col253.png', 'fair', '🐧', true, NULL, 'CMF Series 16 (71013, 2016).', 'A child bundled up in a penguin costume.'),
  ('แบทแมน (Batman Returns 1992)', 'Batman — Batman Returns 1992', 'DC Super Heroes', '30653', '1992 (LEGO 2023)', 20230101, 'pop', 'sh0880', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/sh0880.png', 'sure', '🦇', true, NULL, 'LEGO DC polybag 30653 (2023), a tribute build.', 'Michael Keaton''s Batman from Tim Burton''s 1992 film Batman Returns.'),
  ('แคทแมน', 'Catman', 'The LEGO Batman Movie Series 1', '71017', '2017', 20170201, 'pop', 'coltlbm16', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/coltlbm16.png', 'sure', '🐱', true, NULL, 'The LEGO Batman Movie CMF Series 1 (71017, 2017).', 'Catman, a campy clawed DC villain spoofed in the movie.'),
  ('เฮดีส', 'Hades', 'Disney Series 2', '71024', '2019', 20190210, 'myth', 'dis036', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/dis036.png', 'sure', '🔥', true, NULL, 'LEGO Disney CMF Series 2 (71024, 2019).', 'Hades, the blue-flamed lord of the Underworld from Disney''s Hercules.'),
  ('เพรซิเดนต์ บิสเนส', 'President Business', 'The LEGO Movie Series 1', '71004', '2014', 20140110, 'pop', 'tlm002', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/tlm002.png', 'sure', '🎷', true, NULL, 'The LEGO Movie CMF Series (71004, 2014).', 'Lord/President Business, the order-obsessed villain of The LEGO Movie.'),
  ('เจมส์ บอนด์ 007', 'James Bond (007)', 'Speed Champions', '76911', '2022', 20220110, 'pop', 'sc102', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/sc102.png', 'sure', '🎩', true, NULL, 'LEGO Speed Champions 007 Aston Martin DB5 (76911, 2022).', 'James Bond (Daniel Craig) in his tuxedo, from No Time to Die.'),
  ('โดมินิค โทเร็ตโต้', 'Dominic Toretto', 'Speed Champions', '76912', '2022', 20220120, 'pop', 'sc103', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/sc103.png', 'sure', '👤', true, NULL, 'Speed Champions 1970 Dodge Charger R/T (76912, 2022).', 'Dom Toretto, the family-first street racer of Fast & Furious.'),
  ('ไบรอัน โอคอนเนอร์', 'Brian O''Conner', 'Speed Champions', '76917', '2023', 20230110, 'pop', 'sc104', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/sc104.png', 'sure', '🤍', true, NULL, 'Speed Champions 2 Fast 2 Furious Nissan Skyline GT-R (76917, 2023).', 'Brian O''Conner, ex-cop turned racer in the Fast & Furious saga.'),
  ('ชุดข้าวโพด', 'Corn Cob Guy', 'Series 17', '71018', 'May 2017', 20170501, 'food', 'col289', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col289.png', 'sure', '🌽', true, NULL, 'CMF Series 17 (71018, 2017).', 'A man dressed as an ear of corn on the cob.'),
  ('ชุดมังกรแดง', 'Dragon Suit Guy', 'Series 18', '71021', 'Apr 2018', 20180401, 'myth', 'col318', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col318.png', 'sure', '🐉', true, NULL, 'CMF Series 18 (71021, 2018), the 40th-anniversary ''party'' wave.', 'A festive dragon costume.'),
  ('ชุดพลุ (BANG)', 'Firework Guy', 'Series 18', '71021', 'Apr 2018', 20180402, 'other', 'col316', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col316.png', 'sure', '🎆', true, NULL, 'CMF Series 18 (71021, 2018).', 'A ''BANG!'' firework-rocket costume for celebrations.'),
  ('ชุดกระบองเพชร', 'Cactus Girl', 'Series 18', '71021', 'Apr 2018', 20180403, 'food', 'col322', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col322.png', 'sure', '🌵', true, NULL, 'CMF Series 18 (71021, 2018).', 'A prickly cactus costume.'),
  ('ชุดยีราฟ', 'Giraffe Guy', 'The LEGO Movie 2', '71023', 'Feb 2019', 20190201, 'animal', 'tlm151', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/tlm151.png', 'sure', '🦒', true, NULL, 'The LEGO Movie 2 CMF (71023, 2019).', 'A tall giraffe onesie costume.'),
  ('ชุดสีเทียน', 'Crayon Girl', 'The LEGO Movie 2', '71023', 'Feb 2019', 20190202, 'other', 'tlm152', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/tlm152.png', 'sure', '🖍️', true, NULL, 'The LEGO Movie 2 CMF (71023, 2019).', 'A colourful crayon costume.'),
  ('ชุดแตงโม', 'Watermelon Dude', 'The LEGO Movie 2', '71023', 'Feb 2019', 20190203, 'food', 'tlm155', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/tlm155.png', 'sure', '🍉', true, NULL, 'The LEGO Movie 2 CMF (71023, 2019).', 'A juicy watermelon-slice costume.'),
  ('ชุดพิซซ่า', 'Pizza Costume Guy', 'Series 19', '71025', 'Sep 2019', 20190901, 'food', 'col351', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col351.png', 'sure', '🍕', true, NULL, 'CMF Series 19 (71025, 2019).', 'A man dressed as a slice of pizza.'),
  ('ชุดถั่วลันเตา', 'Peapod Costume Girl', 'Series 20', '71027', '2020', 20200101, 'food', 'col360', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col360.png', 'sure', '🫛', true, NULL, 'CMF Series 20 (71027, 2020).', 'A girl tucked inside a pea-pod costume.'),
  ('ชุดลามา', 'Llama Costume Girl', 'Series 20', '71027', '2020', 20200102, 'animal', 'col364', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col364.png', 'sure', '🦙', true, NULL, 'CMF Series 20 (71027, 2020).', 'A fluffy llama costume.'),
  ('เด็กชุดไก่ (ส้ม)', 'Chicken Suit Boy', 'Build-A-Minifigure', 'BAM 2022', '2022', 20220101, 'animal', 'hol299', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/hol299.png', 'sure', '🐥', true, NULL, 'LEGO Build-A-Minifigure (BAM) station exclusive, 2022.', 'A kid in a bright orange chick/chicken suit.'),
  ('ชุดไก่งวง', 'Turkey Costume', 'Series 23', '71034', 'Sep 2022', 20220901, 'animal', 'col406', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col406.png', 'sure', '🦃', true, NULL, 'CMF Series 23 (71034, 2022).', 'A Thanksgiving turkey costume.'),
  ('ชุดมังกรเขียว', 'Green Dragon Costume', 'Series 23', '71034', 'Sep 2022', 20220902, 'myth', 'col409', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col409.png', 'sure', '🐲', true, NULL, 'CMF Series 23 (71034, 2022).', 'A green dragon costume, companion to earlier dragon suits.'),
  ('ชุดป๊อปคอร์น', 'Popcorn Costume', 'Series 23', '71034', 'Sep 2022', 20220903, 'food', 'col404', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col404.png', 'sure', '🍿', true, NULL, 'CMF Series 23 (71034, 2022).', 'A movie-night popcorn-bucket costume.'),
  ('อัศวินแวมไพร์', 'Vampire Knight', 'Series 25', '71045', '2024', 20240101, 'castle', 'col426', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col426.png', 'sure', '🧛', true, NULL, 'CMF Series 25 (71045, 2024).', 'A vampiric knight with bat-wing helm, bat shield and axe.'),
  ('ราชาอัศวินม้า', 'Horse Knight King', 'Castle (set 31168)', '31168', '2025', 20250801, 'castle', 'cas592', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/cas592.png', 'sure', '🐎', true, NULL, 'LEGO Creator 3-in-1 Medieval Horse Knight Castle (31168, 2025).', 'King of the new Horse Knights faction, reviving the Castle theme.'),
  ('แบทแมนเงือก', 'Mermaid Batman', 'The LEGO Batman Movie Series 2', '71020', '2018', 20180105, 'pop', 'coltlbm29', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/coltlbm29.png', 'sure', '🧜', true, NULL, 'The LEGO Batman Movie CMF Series 2 (71020, 2018).', 'A gag ''merman'' Batman from the movie''s wacky costume line-up.'),
  ('สาวชุดสตรอว์เบอร์รีเค้ก', 'Strawberry Shortcake Girl', 'Build-A-Minifigure', 'BAM 2023', '2023', 20230601, 'food', 'hol355x', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/strawberry.jpg', 'sure', '🍓', true, NULL, 'LEGO Build-A-Minifigure exclusive, 2023.', 'A girl in a strawberry-shortcake slice costume with tie-dye shirt.'),
  ('เฮอร์คิวลิส', 'Hercules', 'Disney Series 2', '71024', '2019', 20190215, 'myth', 'dis037', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/dis037.png', 'sure', '🏛️', true, NULL, 'LEGO Disney CMF Series 2 (71024, 2019).', 'Hercules, the demigod hero of Disney''s Hercules.'),
  ('ชุดสีเทียนม่วงแดง', 'Magenta Crayon Costume Guy', 'Build-A-Minifigure', 'BAM 2023', '2023', 20230610, 'other', NULL, 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/magenta-crayon.webp', 'sure', '🖍️', true, NULL, 'LEGO Build-A-Minifigure exclusive, 2023.', 'A bright magenta crayon costume.'),
  ('นายกฯ ชุดข้าวโพด (Solomon Fleck)', 'Mayor Solomon Fleck (Corn Cob)', 'LEGO City', 'cty1222', '2020', 20200601, 'food', 'cty1222', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/cty1222.png', 'sure', '🌽', true, NULL, 'LEGO Hidden Side / City figure (cty1222).', 'Mayor Solomon Fleck in a corn-cob mascot suit from Hidden Side''s town of Newbury.'),
  ('ชุดเค้ก/พาย', 'Cake / Pie Costume Guy', 'Build-A-Minifigure', 'BAM 2022', '2022', 20220115, 'food', 'hol296', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/hol296.png', 'sure', '🥧', true, NULL, 'LEGO Build-A-Minifigure exclusive, 2022.', 'A sweet slice-of-cake / pie costume.'),
  ('ปาร์ตี้ บานาน่า', 'Party Banana Guy', 'Party Banana Juice Bar', '5005250', '2018', 20181001, 'food', 'col330', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col330.png', 'sure', '🍌', true, NULL, 'Party Banana Juice Bar promo set (5005250, 2018).', 'A dancing banana-suit guy with a boombox.'),
  ('ราชินีอียิปต์', 'Egyptian Queen', 'Series 5', '8805', '2011', 20110902, 'myth', 'col078', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col078.png', 'sure', '🐍', true, NULL, 'CMF Series 5 (set 8805, 2011).', 'An Egyptian queen in the spirit of Cleopatra, complete with a pet snake.'),
  ('ราชินี', 'Queen', 'Series 15', '71011', 'Jan 2016', 20160103, 'castle', 'col243', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col243.png', 'sure', '👸', true, NULL, 'CMF Series 15 (71011, 2016).', 'A regal castle queen with crown and ermine-trimmed cape.'),
  ('กัปตันโจรสลัด (Redbeard)', 'Pirate Captain (Redbeard)', 'Pirates', NULL, '1989', 19890101, 'pirate', 'pi055', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/pi055.png', 'sure', '🏴‍☠️', true, NULL, 'A classic LEGO Pirates captain, from the original 1989 Pirates theme.', 'A swashbuckling pirate captain with skull-and-crossbones hat, hook hand and peg leg.'),
  ('ทหารอิมพีเรียล (Bluecoat)', 'Imperial Soldier', 'Pirates', NULL, '1996', 19960101, 'pirate', 'pi061', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/pi061.png', 'sure', '🪖', true, NULL, 'LEGO Pirates ''Bluecoats'' Imperial Soldiers faction (mid-1990s).', 'A Napoleonic-style naval soldier who pursued LEGO''s pirates.'),
  ('ชุดนกยูง', 'Peacock Costume', 'Series 28', '71051', 'Jan 2026', 20260101, 'animal', 'col461', 'https://qmmopgyevfuztpqaynww.supabase.co/storage/v1/object/public/minifigs/col461.png', 'sure', '🦚', true, NULL, 'CMF Series 28 (71051, 2026), the latest wave.', 'A proud peacock costume with a fanned tail of feathers.');
